# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI geeup

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
      steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python-version }}
      - name: Install Dependencies (Mac)
        continue-on-error: true
        run: python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install wheel
        if: matrix.os == 'macos-latest'
      - name: Install Dependencies (Windows)
        continue-on-error: true
        run: python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install wheel
        if: matrix.os == 'windows-latest'
      - name: Build and install package
        uses: pypa/build@v1
        with:
          publish: true

      - name: Install package
        uses: pypa/installer@v1
        with:
          wheel-ref: dist/*.whl
